stages:
  - build

variables:
  REPODEST: /home/builder/packages/${CI_COMMIT_REF_NAME}/
  S3_DEST: s3://artellectual.apk.build/packages/${CI_COMMIT_REF_NAME}/
  GIT_STRATEGY: fetch

build:
  stage: build
  only:
    refs:
      - master
      - develop
  tags:
    - alpine-sdk
  script:
    - "cd .apk/artello/gitlab-runner"
    - "abuild snapshot"
    - "abuild -r"
    - "s3cmd sync ${S3_DEST} ${REPODEST}"
    - "abuild cleanoldpkg"
    - "s3cmd sync --delete-removed ${REPODEST} ${S3_DEST}"